### ISSUE TITLE
Unable to Sign in using Google Plus

### ISSUE THREAD

**Issue by KeerthanR** [IAR-Webops/IITMConnect#11]
![image](https://cloud.githubusercontent.com/assets/12508015/7696907/02672f62-fe20-11e4-95dc-5b729d84eb0f.png)

I ran into the error shown above, when trying to sign in with my google plus account. Since I'm not on Facebook or LinkedIn, I can't register unless this bug is fixed. Please help.

Thanks.

**Comment by yashmurty** [comment]
@KeerthanR, it seems that you have not set your Gender at the Basic information in Google plus. Kindly set it and you wont face this issue.
