### ISSUE TITLE
Unable to signup through LinkedIn

### ISSUE THREAD

**Issue by gvamshi** [IAR-Webops/IITMConnect#12]
Unable to signup through linkedin if profile picture of linkedin account doesnt exist. PFA the screenshot
![screenshot 94](https://cloud.githubusercontent.com/assets/5681344/7926994/74751d08-08f7-11e5-9ef2-56303ac24aa7.png)

**Comment by yashmurty** [comment]
@gvamshi Kindly add a profile pic on linkedin before trying to create an account on iitmconnect.
