### ISSUE TITLE
variables from oauth unchecked

### ISSUE THREAD

**Issue by dharanimanne** [IAR-Webops/IITMConnect#3]
![error_iitmconnect](https://cloud.githubusercontent.com/assets/2361904/7069142/bf60b994-def4-11e4-9c5d-d497122611d0.png)
If a field is not provided by the oauth sevice provider, the page displays a null error. This is verified for the "pictureUrl" field from linked in.

**Comment by yashmurty** [comment]
@dharanimanne, I have pushed a fix for this issue.
Can you see if the problem still persists.
