### ISSUE TITLE
Not Updating

### ISSUE THREAD

**Issue by abhiramyeluri** [IAR-Webops/IITMConnect#6]
Department , Minor and year of passing out are not updating in basic information tab

**Comment by yashmurty** [comment]
@abhiramyeluri, It was actually getting updated, but it wasn't notifying the changes properly. 
I have now added a text that displays the saved choices.

**Comment by abhiramyeluri** [comment]
Yeah got it.

Y.ABHIRAM SAI,
NA11B034,
Final year undergraduate student,
Naval Arch and Ocean Engg,
IIT Madras,
Ph no: 9940588850.
