### ISSUE TITLE
Roll number mistake

### ISSUE THREAD

**Issue by RohithBhandru** [IAR-Webops/IITMConnect#7]
Hi, when i created my account first, by mistake, i clicked the enter button before completing my roll number. How to change the roll number now?
![mistake](https://cloud.githubusercontent.com/assets/12082119/7294457/3fcb9c62-e9cb-11e4-97db-c597b9a02063.png)

**Comment by yashmurty** [comment]
@RohithBhandru, we don't provide an option to change the roll number. 
We have modified your roll number after checking across our records. 
Let us know if you face any other issues.
