### ISSUE TITLE
Mandatory fields for undergrads to be checked

### ISSUE THREAD

**Issue by dharanimanne** [IAR-Webops/IITMConnect#8]
There is this field called "Project Guide" which should not be mandatory for undergrads because only final years have a project guide. Students in sophomore years or lower should be allowed to leave the field blank. This is one reason some people cannot update their information.

**Comment by shaabhishek** [comment]
@dharanimanne: oh is it compulsory right now?

**Comment by dharanimanne** [comment]
Yes. I could not update my data due to that field after filling out the remaining form.

**Comment by yashmurty** [comment]
Since the initial target audience was final years, i had kept this compulsory. 
Has been modified now.
